version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker

      - restore_cache:
          keys:
            - deps-root-{{ checksum "package.json" }}
            - deps-root

      - restore_cache:
          keys:
            - deps-client-react-{{ checksum "packages/client-react/package.json" }}
            - deps-client-react

      - restore_cache:
          keys:
            - deps-connector-google-drive-v2-{{ checksum "packages/connector-google-drive-v2/package.json" }}
            - deps-connector-google-drive-v2

      - restore_cache:
          keys:
            - deps-connector-node-v1-{{ checksum "packages/connector-node-v1/package.json" }}
            - deps-connector-node-v1

      - restore_cache:
          keys:
            - deps-server-nodejs-{{ checksum "packages/server-nodejs/package.json" }}
            - deps-server-nodejs

      - run:
          name: bootstrap-packages
          command: yarn

      - run:
          name: build-client-static
          command: |
            cd packages/client-react &&
            npm run gh-pages:build &&
            mv ./.gh-pages-tmp ../../demo && mv ../../demo/.gh-pages-tmp ../../demo/static

      - run:
          name: build-server-api-docs
          command: |
            echo 'export SERVER_URL=$SERVER_URL' >> $BASH_ENV &&
            cd packages/server-nodejs && npm run build-api-docs && mkdir -p ../../demo/static/api && cp -r api-docs.tmp/docs ../../demo/static/api

      - run:
          name: install-demo-dependencies
          command: (cd demo && yarn install)

      - run:
          name: build-demo
          command: docker build -f Dockerfile.demo -t ockvolkovich/filemanager-demo:latest .

      - run:
          name: deploy-demo
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push ockvolkovich/filemanager-demo:latest

      - save_cache:
          paths:
            - node_modules
          key: deps-root-{{ checksum "package.json" }}

      - save_cache:
          paths:
            - packages/client-react/node_modules
          key: deps-client-react-{{ checksum "packages/client-react/package.json" }}

      - save_cache:
          paths:
            - packages/connector-google-drive-v2/node_modules
          key: deps-connector-google-drive-v2-{{ checksum "packages/connector-google-drive-v2/package.json" }}

      - save_cache:
          paths:
            - packages/connector-node-v1/node_modules
          key: deps-connector-node-v1-{{ checksum "packages/connector-node-v1/package.json" }}

      - save_cache:
          paths:
            - packages/server-nodejs/node_modules
          key: deps-server-nodejs-{{ checksum "packages/server-nodejs/package.json" }}
