version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: bootstrap-packages
          command: yarn

      - run:
          name: build-client-static
          command: |
            cd packages/client-react &&
            npm run gh-pages:build &&
            mv ./.gh-pages-tmp ../../demo && mv ../../demo/.gh-pages-tmp ../../demo/static

      - run:
          name: build-server-api-docs
          command: |
            echo 'export SERVER_URL=$SERVER_URL' >> $BASH_ENV &&
            cd packages/server-nodejs && npm run build-api-docs && mkdir -p ../../demo/static/api && cp -r api-docs.tmp/docs ../../demo/static/api

      - run:
          name: install-demo-dependencies
          command: (cd demo && yarn install)

      - run:
          name: build-demo
          command: docker build -f Dockerfile.demo -t ockvolkovich/filemanager-demo:latest .

      - run:
          name: deploy-demo
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push ockvolkovich/filemanager-demo:latest
